apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 300
  progressDeadlineSeconds: 900
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebapp
        image: 915316342843.dkr.ecr.us-east-1.amazonaws.com/repositoryforgithub:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
