name: first github actions
on:
  push:
    branches:
      - main
    pull_request:
      - main
    workflow_dispatch:
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v3
